# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Retrieves info about action runner

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  dump-info:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Curl icanhazip
        id: curl-ip
        run: |
          curl icanhazip.com 2>/dev/null
      - name: Get CPU Info
        id: cpuinfo
        run: |
          cat /proc/cpuinfo
      - name: Install traceroute
        id: traceroute
        run: |
          sudo apt-get install traceroute -y
      - name: Trace Home (IPv4)
        id: trace-ipv4
        run: |
          traceroute gp.mace.au
      - name: Trace Home (IPv6)
        id: trace-ipv6
        run: |
          traceroute6 containers.mace.au
          
